[package]
name = "protobufts"
version = "0.1.0"
edition = "2021"
authors = ["Andrii Biletskyi <andrewbeletskiy@gmail.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-clean = "0.1.0"

[[bin]]
name = "protobufts"
path = "main.rs"
