[package]
name = "protobufts"
version = "0.1.0"
edition = "2021"
authors = ["Andrii Biletskyi <andrewbeletskiy@gmail.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# cargo watch -x 'run -- ./test-folder --out ./out'
# RUSTFLAGS=-Awarnings cargo watch -x 'run -- ./test-folder --out ./out'
# ./target/release/protobufts.exe ./test-folder --out out


[dependencies]
path-clean = "0.1.0"

[[bin]]
name = "protobufts"
path = "main.rs"
